module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: 'src',
  testMatch: ['**/test/**/*.spec.ts'],
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: ['**/*.(t|j)s'],
  coverageDirectory: '../coverage',
  testEnvironment: 'node',
  moduleNameMapper: {
    '^src/(.*)$': '<rootDir>/$1',
  },
  testPathIgnorePatterns: [
    '<rootDir>/appModule.ts',
    '<rootDir>/main.ts',
    '<rootDir>/application/dto',
    '<rootDir>/application/filters',
    '<rootDir>/application/jobs',
    '<rootDir>/domain/entities',
    '<rootDir>/domain/enum',
    '<rootDir>/domain/interfaces',
    '<rootDir>/domain/models',
    '<rootDir>/infrastructure/',
    '<rootDir>/config/',
    '<rootDir>/migration/',
    '<rootDir>/modules/',
  ],
  coveragePathIgnorePatterns: [
    '<rootDir>/appModule.ts',
    '<rootDir>/main.ts',
    '<rootDir>/application/dto',
    '<rootDir>/application/filters',
    '<rootDir>/application/jobs',
    '<rootDir>/domain/entities',
    '<rootDir>/domain/enum',
    '<rootDir>/domain/interfaces',
    '<rootDir>/domain/models',
    '<rootDir>/infrastructure/',
    '<rootDir>/config/',
    '<rootDir>/migration/',
    '<rootDir>/modules/',
  ],
};
