name: 'Validate Code'

on:
  pull_request:
    branches: [main, develop]
  workflow_dispatch: {}

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Run TypeScript compiler
        run: npm run build

      - name: Run ESLint
        run: npm run lint

      - name: Run Jest coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: npm run test:cov
          github-token: ${{ secrets.GITHUB_TOKEN }}
